[package]
name = "kernel-riscv"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
path = "src/main_riscv.rs"

[dependencies]
riscv = "0.11"
spin = "0.10"
log = "0.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
